blueprint:
  name: Calibrate Sonoff TRV external temperature with decimal input
  description: Calibrate Sonoff TRVZB internal temperature according to external temperature sensor with decimal approximation
  domain: automation
  input:
    external_temp:
      name: Select the external temp sensor
      description: This will be your external temp sensor.
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    climate_names:
      name: Climate entries
      description: This will be the Sonoff TRVZBs that will be calibrated using the external sensor.
      selector:
        entity:
          domain:
          - climate
          multiple: true
  source_url: https://github.com/kotnik/HASonoffAutomation/blob/main/blueprints/calib_trv_external_temp_v5.yaml
alias: Calibrate Sonoff TRVZBs
description: ''
variables:
  climate_names: !input climate_names
  external_temperature: !input external_temp
trigger:
- platform: state
  entity_id: !input external_temp
  for:
    hours: 0
    minutes: 1
    seconds: 0
    milliseconds: 0
- platform: state
  entity_id: !input climate_names
  for:
    hours: 0
    minutes: 1
    seconds: 0
    milliseconds: 0
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ states(external_temperature) != ''unavailable'' }}'
  - condition: template
    value_template: '{{ states(external_temperature) != ''unknown'' }}'
action:
- repeat:
    for_each: "{{ climate_names }}"
    sequence:
    - variables:
        climate_name: "{{ repeat.item }}"
        device_calib: "number.{{ climate_name.removeprefix('climate.').removesuffix('_thermostat') }}_local_temperature_offset"
        actual_calib: "{{ states(device_calib) | float() }}"
        external_temp: "{{ states(external_temperature) | float() }}"
        device_temp: "{{ state_attr(climate_name, 'current_temperature') | float() }}"
        real_device_temp: "{{ device_temp - actual_calib }}"
        target_calib: "{{ external_temp - real_device_temp }}"
        target_calib_round: "{{ target_calib | round() }}"
        target_calib_trunc: "{{ [ ([target_calib_round, 9] | min), -9 ] | max }}"

    - alias: "check if calibration needs change"
      condition: template
      value_template: "{{ actual_calib != target_calib_trunc }}"
      
    - service: number.set_value
      target:
        entity_id: "{{ device_calib }}"
      data:
        value: "{{ target_calib_trunc }}"

- delay: 5
mode: single
max_exceeded: silent
